#!/bin/sh
# Latency statistics from /proc/latency_stats
# The statistics are resetted before running the benchmark and collected after the test finishes.



# reference code: linux/kernel/latencytop.c

[ -f "/proc/latency_stats" ] || exit 0

snapshot()
{
	echo time: $(date +%s.%N)
	cat /proc/latency_stats
}

echo 0 > /proc/latency_stats
echo -n 1 > /proc/sys/kernel/latencytop

. $LKP_SRC/lib/wait.sh
setup_wait

wait_post_test
snapshot
echo -n 0 > /proc/sys/kernel/latencytop
