#!/bin/sh
# Uptime since boot
# Print the following when the test finishes.
# - time: seconds since epoch
# - boot: seconds since the system is up
# - idle: the amount of time (in seconds) when a CPU is idle (sum of all CPUs)


. $LKP_SRC/lib/wait.sh
setup_wait

snapshot()
{
	echo time: $(date +%s.%N)
	read boot idle < /proc/uptime
	echo boot: $boot
	echo idle: $idle
}

wait_post_test

snapshot
